In [1]:
! pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

MODULE 1 :
Task 1

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
df = pd.DataFrame(columns=[
    "title",
    "price",
    "star_rating",
    "availability",
    "category"
])

print(df)

Empty DataFrame
Columns: [title, price, star_rating, availability, category]
Index: []

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Define an empty DataFrame
df = pd.DataFrame(columns=[
    "title",
    "price",
    "star_rating",
    "availability",
    "category"
])

# Website URL
base_url = "https://books.toscrape.com/catalogue/"

# List to store scraped book data
books = []

# Scrape first 5 pages
for page in range(1, 6):

    # Page 1 has a different URL
    if page == 1:
        url = base_url + "page-1.html"
    else:
        url = base_url + f"page-{page}.html"

    # Send request
    response = requests.get(url)

    # Check whether request was successful
    response.raise_for_status()

    # Parse HTML
    soup = BeautifulSoup(response.text, "html.parser")

    # Find all books on the page
    products = soup.find_all("article", class_="product_pod")

    # Extract information from each book
    for product in products:

        # Title
        title = product.find("h3").find("a")["title"]

        # Price
        price = product.find("p", class_="price_color").text.strip()

        # Star rating
        rating_class = product.find("p", class_="star-rating")["class"]
        star_rating = rating_class[1]

        # Availability
        availability = product.find(
            "p", class_="instock availability"
        ).get_text(strip=True)

        # Category
        # Category is obtained from the individual book page
        book_link = product.find("h3").find("a")["href"]

        book_url = requests.compat.urljoin(url, book_link)

        book_response = requests.get(book_url)
        book_response.raise_for_status()

        book_soup = BeautifulSoup(
            book_response.text,
            "html.parser"
        )

        breadcrumb = book_soup.find("ul", class_="breadcrumb")

        category = breadcrumb.find_all("li")[-2].get_text(strip=True)

        # Store the book information
        books.append({
            "title": title,
            "price": price,
            "star_rating": star_rating,
            "availability": availability,
            "category": category
        })


# Convert scraped data into DataFrame
df = pd.DataFrame(books)

# Display the first 10 rows
print(df.head(10))

                                               title    price star_rating  \
0                               A Light in the Attic  Â£51.77       Three
1                                 Tipping the Velvet  Â£53.74         One
2                                         Soumission  Â£50.10         One
3                                      Sharp Objects  Â£47.82        Four
4              Sapiens: A Brief History of Humankind  Â£54.23        Five
5                                    The Requiem Red  Â£22.65         One
6  The Dirty Little Secrets of Getting Your Dream...  Â£33.34        Four
7  The Coming Woman: A Novel Based on the Life of...  Â£17.93       Three
8  The Boys in the Boat: Nine Americans and Their...  Â£22.60        Four
9                                    The Black Maria  Â£52.15         One

  availability            category
0     In stock              Poetry
1     In stock  Historical Fiction
2     In stock             Fiction
3     In stock             Mystery
4     In stock             History
5     In stock         Young Adult
6     In stock            Business
7     In stock             Default
8     In stock             Default
9     In stock              Poetry

In [5]:
print("Number of books:", len(df))

Number of books: 100

In [6]:
print(df.columns)

Index(['title', 'price', 'star_rating', 'availability', 'category'], dtype='object')

In [7]:
df

,title,price,star_rating,availability,category
0,A Light in the Attic,Â£51.77,Three,In stock,Poetry
1,Tipping the Velvet,Â£53.74,One,In stock,Historical Fiction
2,Soumission,Â£50.10,One,In stock,Fiction
3,Sharp Objects,Â£47.82,Four,In stock,Mystery
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,History
...,...,...,...,...,...
95,Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...,Â£19.92,Two,In stock,Sequential Art
96,"Layered: Baking, Building, and Styling Spectac...",Â£40.11,One,In stock,Food and Drink
97,Judo: Seven Steps to Black Belt (an Introducto...,Â£53.90,Two,In stock,Add a comment
98,Join,Â£35.67,Five,In stock,Science Fiction
99,In the Country We Love: My Family Divided,Â£22.00,Four,In stock,Nonfiction

In [8]:
df.to_csv("books_data.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

In [9]:
from google.colab import files

files.download("books_data.csv")

In [10]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nMissing values:")
print(df.isnull().sum())

print("\nCategories:")
print(df["category"].value_counts())

print("\nStar ratings:")
print(df["star_rating"].value_counts())

Rows: 100
Columns: 5

Missing values:
title           0
price           0
star_rating     0
availability    0
category        0
dtype: int64

Categories:
category
Sequential Art        14
Nonfiction            12
Default                9
Poetry                 7
Fiction                5
Food and Drink         5
Add a comment          5
Young Adult            4
History                4
Fantasy                4
Mystery                3
Music                  3
Childrens              3
Thriller               3
Philosophy             2
Romance                2
Spirituality           2
Science Fiction        2
Politics               1
Business               1
Historical Fiction     1
Travel                 1
Art                    1
Contemporary           1
New Adult              1
Science                1
Health                 1
Horror                 1
Self Help              1
Name: count, dtype: int64

Star ratings:
star_rating
Three    22
One      22
Five     19
Two      19
Four     18
Name: count, dtype: int64

In [11]:
import pandas as pd

# DataFrame created from Task 1
print(df.head())
print(df.columns)

                                   title    price star_rating availability  \
0                   A Light in the Attic  Â£51.77       Three     In stock
1                     Tipping the Velvet  Â£53.74         One     In stock
2                             Soumission  Â£50.10         One     In stock
3                          Sharp Objects  Â£47.82        Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23        Five     In stock

             category
0              Poetry
1  Historical Fiction
2             Fiction
3             Mystery
4             History
Index(['title', 'price', 'star_rating', 'availability', 'category'], dtype='object')

In [12]:
import pandas as pd

df = pd.read_csv("books_data.csv")

print(df.head())

                                   title    price star_rating availability  \
0                   A Light in the Attic  Â£51.77       Three     In stock
1                     Tipping the Velvet  Â£53.74         One     In stock
2                             Soumission  Â£50.10         One     In stock
3                          Sharp Objects  Â£47.82        Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23        Five     In stock

             category
0              Poetry
1  Historical Fiction
2             Fiction
3             Mystery
4             History

Task 2 :

In [13]:
clean_df = df.copy()

print(clean_df.head())

                                   title    price star_rating availability  \
0                   A Light in the Attic  Â£51.77       Three     In stock
1                     Tipping the Velvet  Â£53.74         One     In stock
2                             Soumission  Â£50.10         One     In stock
3                          Sharp Objects  Â£47.82        Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23        Five     In stock

             category
0              Poetry
1  Historical Fiction
2             Fiction
3             Mystery
4             History

In [14]:
clean_df["price_gbp"] = (
    clean_df["price"]
    .astype(str)
    .str.replace("£", "", regex=False)
    .str.strip()
)

clean_df["price_gbp"] = pd.to_numeric(
    clean_df["price_gbp"],
    errors="coerce"
)

In [15]:
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

In [16]:
clean_df["rating"] = clean_df["star_rating"].map(rating_map)

In [17]:
clean_df["in_stock"] = (
    clean_df["availability"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.contains("in stock", na=False)
)

In [18]:
print(clean_df[["price_gbp", "rating", "in_stock"]].isnull().sum())

price_gbp    100
rating         0
in_stock       0
dtype: int64

Task 3:

In [19]:
clean_df["price_gbp"] = clean_df["price_gbp"].fillna(
    clean_df["price_gbp"].median()
)

clean_df["rating"] = clean_df["rating"].fillna(
    clean_df["rating"].median()
)

In [20]:
clean_df["rating"] = clean_df["rating"].round().astype(int)

In [22]:
GBP_TO_INR = 105.50

clean_df["price_inr"] = (
    clean_df["price_gbp"] * GBP_TO_INR
).round(2)

In [23]:
print(clean_df[[
    "price_gbp",
    "price_inr"
]].head())

   price_gbp  price_inr
0        NaN        NaN
1        NaN        NaN
2        NaN        NaN
3        NaN        NaN
4        NaN        NaN

In [29]:
clean_df = clean_df[[
    "title",
    "price_gbp",
    "price_inr",
    "rating",
    "in_stock",
    "category"
]]

In [30]:
print(clean_df.head())
print(clean_df.info())

                                   title  price_gbp  price_inr  rating  \
0                   A Light in the Attic        NaN        NaN       3
1                     Tipping the Velvet        NaN        NaN       1
2                             Soumission        NaN        NaN       1
3                          Sharp Objects        NaN        NaN       4
4  Sapiens: A Brief History of Humankind        NaN        NaN       5

   in_stock            category
0      True              Poetry
1      True  Historical Fiction
2      True             Fiction
3      True             Mystery
4      True             History
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      100 non-null    object
 1   price_gbp  0 non-null      float64
 2   price_inr  0 non-null      float64
 3   rating     100 non-null    int64
 4   in_stock   100 non-null    bool
 5   category   100 non-null    object
dtypes: bool(1), float64(2), int64(1), object(2)
memory usage: 4.1+ KB
None

In [31]:
print("Missing values:")
print(clean_df.isnull().sum())

print("\nNumber of rows:")
print(len(clean_df))

print("\nNumber of categories:")
print(clean_df["category"].nunique())

Missing values:
title          0
price_gbp    100
price_inr    100
rating         0
in_stock       0
category       0
dtype: int64

Number of rows:
100

Number of categories:
29

In [32]:
print(clean_df["rating"].unique())

[3 1 4 5 2]

Task 4:

In [33]:
import sqlite3

In [34]:
conn = sqlite3.connect("books.db")

print("SQLite database created successfully.")

SQLite database created successfully.

In [35]:
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS categories (
    category_id INTEGER PRIMARY KEY,
    category_name TEXT UNIQUE NOT NULL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS books (
    book_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    price_gbp REAL,
    price_inr REAL,
    rating INTEGER,
    in_stock INTEGER,
    category_id INTEGER,
    FOREIGN KEY (category_id)
        REFERENCES categories(category_id)
)
""")

conn.commit()

print("Tables created successfully.")

Tables created successfully.

In [36]:
categories = clean_df["category"].dropna().unique()

print(categories)

['Poetry' 'Historical Fiction' 'Fiction' 'Mystery' 'History' 'Young Adult'
 'Business' 'Default' 'Sequential Art' 'Music' 'Science Fiction'
 'Politics' 'Travel' 'Thriller' 'Food and Drink' 'Romance' 'Childrens'
 'Nonfiction' 'Art' 'Spirituality' 'Philosophy' 'New Adult' 'Contemporary'
 'Fantasy' 'Add a comment' 'Science' 'Health' 'Horror' 'Self Help']

In [37]:
for category in categories:
    cursor.execute(
        """
        INSERT OR IGNORE INTO categories (category_name)
        VALUES (?)
        """,
        (category,)
    )

conn.commit()

In [38]:
cursor.execute("SELECT * FROM categories")

print(cursor.fetchall())

[(1, 'Poetry'), (2, 'Historical Fiction'), (3, 'Fiction'), (4, 'Mystery'), (5, 'History'), (6, 'Young Adult'), (7, 'Business'), (8, 'Default'), (9, 'Sequential Art'), (10, 'Music'), (11, 'Science Fiction'), (12, 'Politics'), (13, 'Travel'), (14, 'Thriller'), (15, 'Food and Drink'), (16, 'Romance'), (17, 'Childrens'), (18, 'Nonfiction'), (19, 'Art'), (20, 'Spirituality'), (21, 'Philosophy'), (22, 'New Adult'), (23, 'Contemporary'), (24, 'Fantasy'), (25, 'Add a comment'), (26, 'Science'), (27, 'Health'), (28, 'Horror'), (29, 'Self Help')]

In [39]:
for _, row in clean_df.iterrows():

    cursor.execute(
        """
        SELECT category_id
        FROM categories
        WHERE category_name = ?
        """,
        (row["category"],)
    )

    category_id = cursor.fetchone()[0]

    cursor.execute(
        """
        INSERT INTO books
        (title, price_gbp, price_inr, rating, in_stock, category_id)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            row["title"],
            row["price_gbp"],
            row["price_inr"],
            row["rating"],
            int(row["in_stock"]),
            category_id
        )
    )

conn.commit()

print("Books inserted successfully.")

Books inserted successfully.

In [40]:
int(row["in_stock"])

1

In [41]:
cursor.execute("SELECT COUNT(*) FROM books")

print("Books in database:", cursor.fetchone()[0])

Books in database: 100

In [42]:
cursor.execute("SELECT COUNT(*) FROM categories")

print("Categories:", cursor.fetchone()[0])

Categories: 29

Task 5:

In [43]:
query1 = """
SELECT title, price_gbp, rating
FROM books
WHERE rating = 5
"""

result1 = pd.read_sql(query1, conn)

print(result1)

                                                title price_gbp  rating
0               Sapiens: A Brief History of Humankind      None       5
1                                         Set Me Free      None       5
2   Scott Pilgrim's Precious Little Life (Scott Pi...      None       5
3                           Rip it Up and Start Again      None       5
4                          Chase Me (Paris Nights #2)      None       5
5                                          Black Dust      None       5
6   Worlds Elsewhere: Journeys Around Shakespeareâ...      None       5
7   The Four Agreements: A Practical Guide to Pers...      None       5
8                                   The Elephant Tree      None       5
9                                      Sophie's World      None       5
10                        Private Paris (Private #10)      None       5
11  #HigherSelfie: Wake Up Your Life. Free Your So...      None       5
12                       We Love You, Charlie Freeman      None       5
13                                             Thirst      None       5
14  The Inefficiency Assassin: Time Management Tac...      None       5
15  The Activist's Tao Te Ching: Ancient Advice fo...      None       5
16  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...      None       5
17   Princess Between Worlds (Wide-Awake Princess #5)      None       5
18                                               Join      None       5

In [44]:
query1

'\nSELECT title, price_gbp, rating\nFROM books\nWHERE rating = 5\n'

In [45]:
result1

                                                title price_gbp  rating
0               Sapiens: A Brief History of Humankind      None       5
1                                         Set Me Free      None       5
2   Scott Pilgrim's Precious Little Life (Scott Pi...      None       5
3                           Rip it Up and Start Again      None       5
4                          Chase Me (Paris Nights #2)      None       5
5                                          Black Dust      None       5
6   Worlds Elsewhere: Journeys Around Shakespeareâ...      None       5
7   The Four Agreements: A Practical Guide to Pers...      None       5
8                                   The Elephant Tree      None       5
9                                      Sophie's World      None       5
10                        Private Paris (Private #10)      None       5
11  #HigherSelfie: Wake Up Your Life. Free Your So...      None       5
12                       We Love You, Charlie Freeman      None       5
13                                             Thirst      None       5
14  The Inefficiency Assassin: Time Management Tac...      None       5
15  The Activist's Tao Te Ching: Ancient Advice fo...      None       5
16  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...      None       5
17   Princess Between Worlds (Wide-Awake Princess #5)      None       5
18                                               Join      None       5

In [46]:
query2 = """
SELECT title, price_gbp, rating
FROM books
ORDER BY price_gbp DESC
"""

result2 = pd.read_sql(query2, conn)

print(result2)

                                                title price_gbp  rating
0                                A Light in the Attic      None       3
1                                  Tipping the Velvet      None       1
2                                          Soumission      None       1
3                                       Sharp Objects      None       4
4               Sapiens: A Brief History of Humankind      None       5
..                                                ...       ...     ...
95  Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...      None       2
96  Layered: Baking, Building, and Styling Spectac...      None       1
97  Judo: Seven Steps to Black Belt (an Introducto...      None       2
98                                               Join      None       5
99          In the Country We Love: My Family Divided      None       4

[100 rows x 3 columns]

In [48]:
query3 = """
SELECT title, price_gbp
FROM books
ORDER BY price_gbp DESC
LIMIT 10
"""

result3 = pd.read_sql(query3, conn)

print(result3)

                                               title price_gbp
0                               A Light in the Attic      None
1                                 Tipping the Velvet      None
2                                         Soumission      None
3                                      Sharp Objects      None
4              Sapiens: A Brief History of Humankind      None
5                                    The Requiem Red      None
6  The Dirty Little Secrets of Getting Your Dream...      None
7  The Coming Woman: A Novel Based on the Life of...      None
8  The Boys in the Boat: Nine Americans and Their...      None
9                                    The Black Maria      None

In [49]:
query4 = """
SELECT DISTINCT category_name
FROM categories
ORDER BY category_name
"""

result4 = pd.read_sql(query4, conn)

print(result4)

         category_name
0        Add a comment
1                  Art
2             Business
3            Childrens
4         Contemporary
5              Default
6              Fantasy
7              Fiction
8       Food and Drink
9               Health
10  Historical Fiction
11             History
12              Horror
13               Music
14             Mystery
15           New Adult
16          Nonfiction
17          Philosophy
18              Poetry
19            Politics
20             Romance
21             Science
22     Science Fiction
23           Self Help
24      Sequential Art
25        Spirituality
26            Thriller
27              Travel
28         Young Adult

In [50]:
query5 = """
SELECT title, price_gbp, rating
FROM books
WHERE price_gbp BETWEEN 20 AND 40
ORDER BY price_gbp
"""

result5 = pd.read_sql(query5, conn)

print(result5)

Empty DataFrame
Columns: [title, price_gbp, rating]
Index: []

In [51]:
join_query = """
SELECT
    b.title,
    c.category_name,
    b.price_gbp,
    b.rating,
    b.in_stock
FROM books b
JOIN categories c
    ON b.category_id = c.category_id
ORDER BY b.rating DESC, b.title
LIMIT 10
"""

join_result = pd.read_sql(join_query, conn)

print(join_result)

                                               title    category_name  \
0  #HigherSelfie: Wake Up Your Life. Free Your So...       Nonfiction
1                                         Black Dust          Romance
2                         Chase Me (Paris Nights #2)          Romance
3                                               Join  Science Fiction
4   Princess Between Worlds (Wide-Awake Princess #5)          Fantasy
5  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...   Sequential Art
6                        Private Paris (Private #10)          Fiction
7                          Rip it Up and Start Again            Music
8              Sapiens: A Brief History of Humankind          History
9  Scott Pilgrim's Precious Little Life (Scott Pi...   Sequential Art

  price_gbp  rating  in_stock
0      None       5         1
1      None       5         1
2      None       5         1
3      None       5         1
4      None       5         1
5      None       5         1
6      None       5         1
7      None       5         1
8      None       5         1
9      None       5         1

Task 6:

In [52]:
result1 = pd.read_sql(query1, conn)

In [53]:
result3 = pd.read_sql(query3, conn)

In [54]:
print("Query 1 result:")
display(result1)

print("Query 3 result:")
display(result3)

Query 1 result:

                                                title price_gbp  rating
0               Sapiens: A Brief History of Humankind      None       5
1                                         Set Me Free      None       5
2   Scott Pilgrim's Precious Little Life (Scott Pi...      None       5
3                           Rip it Up and Start Again      None       5
4                          Chase Me (Paris Nights #2)      None       5
5                                          Black Dust      None       5
6   Worlds Elsewhere: Journeys Around Shakespeareâ...      None       5
7   The Four Agreements: A Practical Guide to Pers...      None       5
8                                   The Elephant Tree      None       5
9                                      Sophie's World      None       5
10                        Private Paris (Private #10)      None       5
11  #HigherSelfie: Wake Up Your Life. Free Your So...      None       5
12                       We Love You, Charlie Freeman      None       5
13                                             Thirst      None       5
14  The Inefficiency Assassin: Time Management Tac...      None       5
15  The Activist's Tao Te Ching: Ancient Advice fo...      None       5
16  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...      None       5
17   Princess Between Worlds (Wide-Awake Princess #5)      None       5
18                                               Join      None       5

Query 3 result:

                                               title price_gbp
0                               A Light in the Attic      None
1                                 Tipping the Velvet      None
2                                         Soumission      None
3                                      Sharp Objects      None
4              Sapiens: A Brief History of Humankind      None
5                                    The Requiem Red      None
6  The Dirty Little Secrets of Getting Your Dream...      None
7  The Coming Woman: A Novel Based on the Life of...      None
8  The Boys in the Boat: Nine Americans and Their...      None
9                                    The Black Maria      None

In [55]:
join_result = pd.read_sql(join_query, conn)

display(join_result)

,title,category_name,price_gbp,rating,in_stock
0,#HigherSelfie: Wake Up Your Life. Free Your So...,Nonfiction,None,5,1
1,Black Dust,Romance,None,5,1
2,Chase Me (Paris Nights #2),Romance,None,5,1
3,Join,Science Fiction,None,5,1
4,Princess Between Worlds (Wide-Awake Princess #5),Fantasy,None,5,1
5,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",Sequential Art,None,5,1
6,Private Paris (Private #10),Fiction,None,5,1
7,Rip it Up and Start Again,Music,None,5,1
8,Sapiens: A Brief History of Humankind,History,None,5,1
9,Scott Pilgrim's Precious Little Life (Scott Pi...,Sequential Art,None,5,1

In [56]:
categories_df = pd.read_sql(
    "SELECT * FROM categories",
    conn
)

print(categories_df.head())

   category_id       category_name
0            1              Poetry
1            2  Historical Fiction
2            3             Fiction
3            4             Mystery
4            5             History

In [57]:
books_df = pd.read_sql(
    "SELECT * FROM books",
    conn
)

print(books_df.head())

   book_id                                  title price_gbp price_inr  rating  \
0        1                   A Light in the Attic      None      None       3
1        2                     Tipping the Velvet      None      None       1
2        3                             Soumission      None      None       1
3        4                          Sharp Objects      None      None       4
4        5  Sapiens: A Brief History of Humankind      None      None       5

   in_stock  category_id
0         1            1
1         1            2
2         1            3
3         1            4
4         1            5

In [58]:
merge_result = pd.merge(
    books_df,
    categories_df,
    on="category_id",
    how="inner"
)

In [59]:
merge_result = merge_result[[
    "title",
    "category_name",
    "price_gbp",
    "rating",
    "in_stock"
]]

In [60]:
merge_result = merge_result.sort_values(
    by=["rating", "title"],
    ascending=[False, True]
).head(10)

In [61]:
merge_result = merge_result.reset_index(drop=True)

In [62]:
display(merge_result)

,title,category_name,price_gbp,rating,in_stock
0,#HigherSelfie: Wake Up Your Life. Free Your So...,Nonfiction,None,5,1
1,Black Dust,Romance,None,5,1
2,Chase Me (Paris Nights #2),Romance,None,5,1
3,Join,Science Fiction,None,5,1
4,Princess Between Worlds (Wide-Awake Princess #5),Fantasy,None,5,1
5,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",Sequential Art,None,5,1
6,Private Paris (Private #10),Fiction,None,5,1
7,Rip it Up and Start Again,Music,None,5,1
8,Sapiens: A Brief History of Humankind,History,None,5,1
9,Scott Pilgrim's Precious Little Life (Scott Pi...,Sequential Art,None,5,1

In [63]:
sql_compare = join_result.reset_index(drop=True)
pandas_compare = merge_result.reset_index(drop=True)

print(
    sql_compare.equals(pandas_compare)
)

True

In [64]:
print("SQL JOIN:")
display(sql_compare)

print("Pandas merge:")
display(pandas_compare)

SQL JOIN:

,title,category_name,price_gbp,rating,in_stock
0,#HigherSelfie: Wake Up Your Life. Free Your So...,Nonfiction,None,5,1
1,Black Dust,Romance,None,5,1
2,Chase Me (Paris Nights #2),Romance,None,5,1
3,Join,Science Fiction,None,5,1
4,Princess Between Worlds (Wide-Awake Princess #5),Fantasy,None,5,1
5,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",Sequential Art,None,5,1
6,Private Paris (Private #10),Fiction,None,5,1
7,Rip it Up and Start Again,Music,None,5,1
8,Sapiens: A Brief History of Humankind,History,None,5,1
9,Scott Pilgrim's Precious Little Life (Scott Pi...,Sequential Art,None,5,1

Pandas merge:

,title,category_name,price_gbp,rating,in_stock
0,#HigherSelfie: Wake Up Your Life. Free Your So...,Nonfiction,None,5,1
1,Black Dust,Romance,None,5,1
2,Chase Me (Paris Nights #2),Romance,None,5,1
3,Join,Science Fiction,None,5,1
4,Princess Between Worlds (Wide-Awake Princess #5),Fantasy,None,5,1
5,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",Sequential Art,None,5,1
6,Private Paris (Private #10),Fiction,None,5,1
7,Rip it Up and Start Again,Music,None,5,1
8,Sapiens: A Brief History of Humankind,History,None,5,1
9,Scott Pilgrim's Precious Little Life (Scott Pi...,Sequential Art,None,5,1

In [65]:
query_outputs = {
    "query1_select_where": result1,
    "query2_order_by": result2,
    "query3_limit": result3,
    "query4_distinct": result4,
    "query5_between": result5,
    "query6_join": join_result
}

In [66]:
for name, result in query_outputs.items():

    filename = f"{name}.csv"

    result.to_csv(filename, index=False)

    print(f"Saved: {filename}")

Saved: query1_select_where.csv
Saved: query2_order_by.csv
Saved: query3_limit.csv
Saved: query4_distinct.csv
Saved: query5_between.csv
Saved: query6_join.csv

In [67]:
queries_text = f"""
QUERY 1 - SELECT / WHERE
{query1}

QUERY 2 - ORDER BY
{query2}

QUERY 3 - LIMIT
{query3}

QUERY 4 - DISTINCT
{query4}

QUERY 5 - BETWEEN
{query5}

QUERY 6 - JOIN
{join_query}
"""

with open("sql_queries.txt", "w") as file:
    file.write(queries_text)

print("SQL queries saved.")

SQL queries saved.

In [68]:
print("===== FINAL VALIDATION =====")

print("Total scraped/cleaned books:", len(clean_df))

print("Database books:",
      pd.read_sql("SELECT COUNT(*) AS count FROM books", conn)["count"][0])

print("Database categories:",
      pd.read_sql("SELECT COUNT(*) AS count FROM categories", conn)["count"][0])

print("\nMissing values:")
print(clean_df.isnull().sum())

print("\nRating values:")
print(sorted(clean_df["rating"].unique()))

print("\nSQL JOIN equals pandas merge:")
print(sql_compare.equals(pandas_compare))

===== FINAL VALIDATION =====
Total scraped/cleaned books: 100
Database books: 100
Database categories: 29

Missing values:
title          0
price_gbp    100
price_inr    100
rating         0
in_stock       0
category       0
dtype: int64

Rating values:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

SQL JOIN equals pandas merge:
True

In [69]:
import pandas as pd
import sqlite3

# ============================================
# 1. LOAD DATA FROM TASK 1
# ============================================

# If df already exists from Task 1, use it directly.
# Otherwise:
# df = pd.read_csv("books_data.csv")

clean_df = df.copy()


# ============================================
# 2. CLEAN PRICE
# ============================================

clean_df["price_gbp"] = (
    clean_df["price"]
    .astype(str)
    .str.replace("£", "", regex=False)
    .str.strip()
)

clean_df["price_gbp"] = pd.to_numeric(
    clean_df["price_gbp"],
    errors="coerce"
)


# ============================================
# 3. CLEAN RATING
# ============================================

rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

clean_df["rating"] = clean_df["star_rating"].map(rating_map)


# ============================================
# 4. CLEAN AVAILABILITY
# ============================================

clean_df["in_stock"] = (
    clean_df["availability"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.contains("in stock", na=False)
)


# ============================================
# 5. MEDIAN IMPUTATION
# ============================================

clean_df["price_gbp"] = clean_df["price_gbp"].fillna(
    clean_df["price_gbp"].median()
)

clean_df["rating"] = clean_df["rating"].fillna(
    clean_df["rating"].median()
)

clean_df["rating"] = clean_df["rating"].round().astype(int)


# ============================================
# 6. GBP → INR
# ============================================

GBP_TO_INR = 105.50

clean_df["price_inr"] = (
    clean_df["price_gbp"] * GBP_TO_INR
).round(2)


# ============================================
# 7. SELECT FINAL COLUMNS
# ============================================

clean_df = clean_df[[
    "title",
    "price_gbp",
    "price_inr",
    "rating",
    "in_stock",
    "category"
]]

print(clean_df.head())


# ============================================
# 8. CREATE SQLITE DATABASE
# ============================================

conn = sqlite3.connect("books.db")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS categories (
    category_id INTEGER PRIMARY KEY,
    category_name TEXT UNIQUE NOT NULL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS books (
    book_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    price_gbp REAL,
    price_inr REAL,
    rating INTEGER,
    in_stock INTEGER,
    category_id INTEGER,
    FOREIGN KEY (category_id)
        REFERENCES categories(category_id)
)
""")

conn.commit()


# ============================================
# 9. INSERT CATEGORIES
# ============================================

for category in clean_df["category"].dropna().unique():

    cursor.execute(
        """
        INSERT OR IGNORE INTO categories (category_name)
        VALUES (?)
        """,
        (category,)
    )

conn.commit()


# ============================================
# 10. INSERT BOOKS
# ============================================

for _, row in clean_df.iterrows():

    cursor.execute(
        """
        SELECT category_id
        FROM categories
        WHERE category_name = ?
        """,
        (row["category"],)
    )

    category_id = cursor.fetchone()[0]

    cursor.execute(
        """
        INSERT INTO books
        (title, price_gbp, price_inr, rating, in_stock, category_id)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            row["title"],
            row["price_gbp"],
            row["price_inr"],
            row["rating"],
            int(row["in_stock"]),
            category_id
        )
    )

conn.commit()


# ============================================
# 11. SQL QUERY 1: SELECT / WHERE
# ============================================

query1 = """
SELECT title, price_gbp, rating
FROM books
WHERE rating = 5
"""

result1 = pd.read_sql(query1, conn)

print("\nQUERY 1")
display(result1)


# ============================================
# 12. SQL QUERY 2: ORDER BY
# ============================================

query2 = """
SELECT title, price_gbp, rating
FROM books
ORDER BY price_gbp DESC
"""

result2 = pd.read_sql(query2, conn)

print("\nQUERY 2")
display(result2)


# ============================================
# 13. SQL QUERY 3: LIMIT
# ============================================

query3 = """
SELECT title, price_gbp
FROM books
ORDER BY price_gbp DESC
LIMIT 10
"""

result3 = pd.read_sql(query3, conn)

print("\nQUERY 3")
display(result3)


# ============================================
# 14. SQL QUERY 4: DISTINCT
# ============================================

query4 = """
SELECT DISTINCT category_name
FROM categories
ORDER BY category_name
"""

result4 = pd.read_sql(query4, conn)

print("\nQUERY 4")
display(result4)


# ============================================
# 15. SQL QUERY 5: BETWEEN
# ============================================

query5 = """
SELECT title, price_gbp, rating
FROM books
WHERE price_gbp BETWEEN 20 AND 40
ORDER BY price_gbp
"""

result5 = pd.read_sql(query5, conn)

print("\nQUERY 5")
display(result5)


# ============================================
# 16. SQL QUERY 6: JOIN
# ============================================

join_query = """
SELECT
    b.title,
    c.category_name,
    b.price_gbp,
    b.rating,
    b.in_stock
FROM books b
JOIN categories c
    ON b.category_id = c.category_id
ORDER BY b.rating DESC, b.title
LIMIT 10
"""

join_result = pd.read_sql(join_query, conn)

print("\nQUERY 6 - JOIN")
display(join_result)


# ============================================
# 17. REPRODUCE JOIN USING pd.merge()
# ============================================

books_df = pd.read_sql(
    "SELECT * FROM books",
    conn
)

categories_df = pd.read_sql(
    "SELECT * FROM categories",
    conn
)

merge_result = pd.merge(
    books_df,
    categories_df,
    on="category_id",
    how="inner"
)

merge_result = merge_result[[
    "title",
    "category_name",
    "price_gbp",
    "rating",
    "in_stock"
]]

merge_result = merge_result.sort_values(
    by=["rating", "title"],
    ascending=[False, True]
).head(10)

merge_result = merge_result.reset_index(drop=True)


# ============================================
# 18. COMPARE SQL JOIN AND PANDAS MERGE
# ============================================

sql_compare = join_result.reset_index(drop=True)

print("\nSQL JOIN RESULT")
display(sql_compare)

print("\nPANDAS MERGE RESULT")
display(merge_result)

print(
    "\nAre SQL JOIN and pandas merge equivalent?",
    sql_compare.equals(merge_result)
)


# ============================================
# 19. SAVE QUERY OUTPUTS
# ============================================

query_outputs = {
    "query1_select_where": result1,
    "query2_order_by": result2,
    "query3_limit": result3,
    "query4_distinct": result4,
    "query5_between": result5,
    "query6_join": join_result
}

for name, result in query_outputs.items():
    result.to_csv(f"{name}.csv", index=False)


# ============================================
# 20. FINAL VALIDATION
# ============================================

print("\n===== FINAL VALIDATION =====")

print("Total books:", len(clean_df))

print(
    "Books in SQLite:",
    pd.read_sql(
        "SELECT COUNT(*) AS count FROM books",
        conn
    )["count"][0]
)

print(
    "Categories in SQLite:",
    pd.read_sql(
        "SELECT COUNT(*) AS count FROM categories",
        conn
    )["count"][0]
)

print("\nMissing values:")
print(clean_df.isnull().sum())

print("\nRating values:")
print(sorted(clean_df["rating"].unique()))

print(
    "\nJOIN equivalence:",
    sql_compare.equals(merge_result)
)

# Close database
conn.close()

                                   title  price_gbp  price_inr  rating  \
0                   A Light in the Attic        NaN        NaN       3
1                     Tipping the Velvet        NaN        NaN       1
2                             Soumission        NaN        NaN       1
3                          Sharp Objects        NaN        NaN       4
4  Sapiens: A Brief History of Humankind        NaN        NaN       5

   in_stock            category
0      True              Poetry
1      True  Historical Fiction
2      True             Fiction
3      True             Mystery
4      True             History

QUERY 1

                                                title price_gbp  rating
0               Sapiens: A Brief History of Humankind      None       5
1                                         Set Me Free      None       5
2   Scott Pilgrim's Precious Little Life (Scott Pi...      None       5
3                           Rip it Up and Start Again      None       5
4                          Chase Me (Paris Nights #2)      None       5
5                                          Black Dust      None       5
6   Worlds Elsewhere: Journeys Around Shakespeareâ...      None       5
7   The Four Agreements: A Practical Guide to Pers...      None       5
8                                   The Elephant Tree      None       5
9                                      Sophie's World      None       5
10                        Private Paris (Private #10)      None       5
11  #HigherSelfie: Wake Up Your Life. Free Your So...      None       5
12                       We Love You, Charlie Freeman      None       5
13                                             Thirst      None       5
14  The Inefficiency Assassin: Time Management Tac...      None       5
15  The Activist's Tao Te Ching: Ancient Advice fo...      None       5
16  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...      None       5
17   Princess Between Worlds (Wide-Awake Princess #5)      None       5
18                                               Join      None       5
19              Sapiens: A Brief History of Humankind      None       5
20                                        Set Me Free      None       5
21  Scott Pilgrim's Precious Little Life (Scott Pi...      None       5
22                          Rip it Up and Start Again      None       5
23                         Chase Me (Paris Nights #2)      None       5
24                                         Black Dust      None       5
25  Worlds Elsewhere: Journeys Around Shakespeareâ...      None       5
26  The Four Agreements: A Practical Guide to Pers...      None       5
27                                  The Elephant Tree      None       5
28                                     Sophie's World      None       5
29                        Private Paris (Private #10)      None       5
30  #HigherSelfie: Wake Up Your Life. Free Your So...      None       5
31                       We Love You, Charlie Freeman      None       5
32                                             Thirst      None       5
33  The Inefficiency Assassin: Time Management Tac...      None       5
34  The Activist's Tao Te Ching: Ancient Advice fo...      None       5
35  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...      None       5
36   Princess Between Worlds (Wide-Awake Princess #5)      None       5
37                                               Join      None       5

QUERY 2

                                                 title price_gbp  rating
0                                 A Light in the Attic      None       3
1                                   Tipping the Velvet      None       1
2                                           Soumission      None       1
3                                        Sharp Objects      None       4
4                Sapiens: A Brief History of Humankind      None       5
..                                                 ...       ...     ...
195  Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...      None       2
196  Layered: Baking, Building, and Styling Spectac...      None       1
197  Judo: Seven Steps to Black Belt (an Introducto...      None       2
198                                               Join      None       5
199          In the Country We Love: My Family Divided      None       4

[200 rows x 3 columns]

QUERY 3

                                               title price_gbp
0                               A Light in the Attic      None
1                                 Tipping the Velvet      None
2                                         Soumission      None
3                                      Sharp Objects      None
4              Sapiens: A Brief History of Humankind      None
5                                    The Requiem Red      None
6  The Dirty Little Secrets of Getting Your Dream...      None
7  The Coming Woman: A Novel Based on the Life of...      None
8  The Boys in the Boat: Nine Americans and Their...      None
9                                    The Black Maria      None

QUERY 4

         category_name
0        Add a comment
1                  Art
2             Business
3            Childrens
4         Contemporary
5              Default
6              Fantasy
7              Fiction
8       Food and Drink
9               Health
10  Historical Fiction
11             History
12              Horror
13               Music
14             Mystery
15           New Adult
16          Nonfiction
17          Philosophy
18              Poetry
19            Politics
20             Romance
21             Science
22     Science Fiction
23           Self Help
24      Sequential Art
25        Spirituality
26            Thriller
27              Travel
28         Young Adult

QUERY 5

Empty DataFrame
Columns: [title, price_gbp, rating]
Index: []

QUERY 6 - JOIN

,title,category_name,price_gbp,rating,in_stock
0,#HigherSelfie: Wake Up Your Life. Free Your So...,Nonfiction,None,5,1
1,#HigherSelfie: Wake Up Your Life. Free Your So...,Nonfiction,None,5,1
2,Black Dust,Romance,None,5,1
3,Black Dust,Romance,None,5,1
4,Chase Me (Paris Nights #2),Romance,None,5,1
5,Chase Me (Paris Nights #2),Romance,None,5,1
6,Join,Science Fiction,None,5,1
7,Join,Science Fiction,None,5,1
8,Princess Between Worlds (Wide-Awake Princess #5),Fantasy,None,5,1
9,Princess Between Worlds (Wide-Awake Princess #5),Fantasy,None,5,1

SQL JOIN RESULT

,title,category_name,price_gbp,rating,in_stock
0,#HigherSelfie: Wake Up Your Life. Free Your So...,Nonfiction,None,5,1
1,#HigherSelfie: Wake Up Your Life. Free Your So...,Nonfiction,None,5,1
2,Black Dust,Romance,None,5,1
3,Black Dust,Romance,None,5,1
4,Chase Me (Paris Nights #2),Romance,None,5,1
5,Chase Me (Paris Nights #2),Romance,None,5,1
6,Join,Science Fiction,None,5,1
7,Join,Science Fiction,None,5,1
8,Princess Between Worlds (Wide-Awake Princess #5),Fantasy,None,5,1
9,Princess Between Worlds (Wide-Awake Princess #5),Fantasy,None,5,1

PANDAS MERGE RESULT

,title,category_name,price_gbp,rating,in_stock
0,#HigherSelfie: Wake Up Your Life. Free Your So...,Nonfiction,None,5,1
1,#HigherSelfie: Wake Up Your Life. Free Your So...,Nonfiction,None,5,1
2,Black Dust,Romance,None,5,1
3,Black Dust,Romance,None,5,1
4,Chase Me (Paris Nights #2),Romance,None,5,1
5,Chase Me (Paris Nights #2),Romance,None,5,1
6,Join,Science Fiction,None,5,1
7,Join,Science Fiction,None,5,1
8,Princess Between Worlds (Wide-Awake Princess #5),Fantasy,None,5,1
9,Princess Between Worlds (Wide-Awake Princess #5),Fantasy,None,5,1

Are SQL JOIN and pandas merge equivalent? True

===== FINAL VALIDATION =====
Total books: 100
Books in SQLite: 200
Categories in SQLite: 29

Missing values:
title          0
price_gbp    100
price_inr    100
rating         0
in_stock       0
category       0
dtype: int64

Rating values:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

JOIN equivalence: True